environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: 'LTS'
    - nodejs_version: 'Current'

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry yarn install --immutable --immutable-cache

test_script:
  - node --version
  - yarn --version
  - yarn mocha --timeout=10000 ".\test\js\*.js"

build: off
skip_branch_with_pr: true
