version: 2.1

jobs:
  build:
    working_directory: ~/herman
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - herman-yarn-{{ checksum ".pnp.cjs" }}-{{ checksum "yarn.lock" }}
            - herman-yarn-
      - run:
          name: Install Dependencies
          command: yarn install --immutable --immutable-cache
      - run:
          name: Compile Assets
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz
      - save_cache:
          key: herman-yarn-{{ checksum ".pnp.cjs" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz

  lint:
    working_directory: ~/herman
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint:ci

  test:
    working_directory: ~/herman
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Sass
          command: yarn test:sass
      - run:
          name: Test JS
          command: yarn test:js:src:ci
          environment:
            MOCHA_FILE: './coverage/src/junit.xml'
      - run:
          name: Test Client JS
          command: yarn test:js:client:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: './coverage/client'
      - store_artifacts:
          path: coverage
          destination: js-test-reports
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  check-test-coverage:
    working_directory: ~/herman
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report Test Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Check Test Coverage
          command: |
            yarn nyc check-coverage --temp-dir coverage/src
            yarn nyc check-coverage --temp-dir coverage/client

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - check-test-coverage:
          requires:
            - test
